# Project identifiers
sonar.projectKey=TaskTen
sonar.projectName=TaskTen
sonar.projectVersion=1.0

# Paths
sonar.sources=src
sonar.java.binaries=target/classes

# Connection
sonar.host.url=http://localhost:9000
sonar.login=sqa_b67b4ac9005c2acbbab77cbdad143d69fb619212